const express = require('express')
const router = express.Router()
const {verifyAdminToken} = require('../middlewares/jwt')
const Controller = require('../controllers/admin-controller')

router.get('/users', verifyAdminToken(process.env.TOKEN_ACCESS_ADMIN), Controller.getUsers)
router.get('/users/:id', verifyAdminToken(process.env.TOKEN_ACCESS_ADMIN), Controller.getUserById)
router.get('/users/history/:id', verifyAdminToken(process.env.TOKEN_ACCESS_ADMIN), Controller.getHistoryById)
router.get('/products', verifyAdminToken(process.env.TOKEN_ACCESS_ADMIN), Controller.getProducts)
router.get('/product/:id', verifyAdminToken(process.env.TOKEN_ACCESS_ADMIN), Controller.getProductById)
router.get('/product/create', verifyAdminToken(process.env.TOKEN_ACCESS_ADMIN), Controller.createProduct)
router.get('/product/edit/:id', verifyAdminToken(process.env.TOKEN_ACCESS_ADMIN), Controller.editProduct)
router.get('/product/delete/:id', verifyAdminToken(process.env.TOKEN_ACCESS_ADMIN), Controller.deleteProduct)
router.get('/category/create', verifyAdminToken(process.env.TOKEN_ACCESS_ADMIN), Controller.createCategory)
router.get('/category/edit/:id', verifyAdminToken(process.env.TOKEN_ACCESS_ADMIN), Controller.editCategory)
router.get('/category/delete/:id', verifyAdminToken(process.env.TOKEN_ACCESS_ADMIN), Controller.deleteCategory)
router.get('/subcategory', verifyAdminToken(process.env.TOKEN_ACCESS_ADMIN), Controller.createSubcategory)
router.get('/subcategory/edit/:id', verifyAdminToken(process.env.TOKEN_ACCESS_ADMIN), Controller.editSubcategory)
router.get('/subcategory/delete:id', verifyAdminToken(process.env.TOKEN_ACCESS_ADMIN), Controller.deleteSubcategory)

module.exports = router